### ISSUE TITLE
Frontend - Appeal button returned "undefined" when issuing a reject/accept appeal reason

### ISSUE THREAD

**Issue by raylou15** [jaredlyon/Operation-Politibot#93]
this is going to make me kill someone because i fixed this before but it looks like the issue has occurred again and i don't know why.

example: https://discord.com/channels/760275642150420520/893189759474757693/1029982650183712788

**Comment by dblbug** [comment]
this happens due to line 220/320 here: https://github.com/jaredlyon/Operation-Politibot/blob/a4cdcf2919b92412f86f4c6ebe4f44b6b6a49b6b/events/clientEvents/interactionCreate.js#L220

var result is never initialized explicitly, so it defaults to [undefined], which then gets type converted to "undefined" when you pass it in the send() function later on.

would recommend initializing result as "decided" or something similar, since you only ever initialize result if the interactionID is accept/reject - so if you get a timeout or something similar, it gets stuck in limbo

**Comment by raylou15** [comment]
> would recommend initializing result as "decided" or something similar, since you only ever initialize result if the interactionID is accept/reject - so if you get a timeout or something similar, it gets stuck in limbo

still need a way to identify whether a result is accepted or rejected for clarification to other moderators. but var not being initialized is probably the culprit... i'll take a look later but i'm also pretty sure both instances use the same code and only "accept/reject w/ reason" (and not just accept/reject) ends up with undefined. not sure

**Comment by jaredlyon** [comment]
Fixed in 2c1df27.
